return {
	['Available Heads'] = {
		--[0] = ".",
		[1] = "Harlequin Head",
		[2] = "Valoredge Head",
		[3] = "Sharpshot Head",
		[4] = "Stormwaker Head",
		[5] = "Soulsoother Head",
		[6] = "Spiritreaver Head",
	},
	['Available Bodies'] = {
		[0] = "Harlequin Frame",
		[1] = "Valoredge Frame",
		[2] = "Sharpshot Frame",
		[3] = "Stormwaker Frame",
	},
	['Fire Attachments'] = {
		--[0] = ".",
		[1] = "Strobe",
		[2] = "Tension Spring",
		[3] = "Inhibitor",
		[4] = "Tension Spring II",
		[5] = "Attuner",
		[6] = "Reactive Shield",
		[7] = "Flame Holder",
		[8] = "Heat Capacitor",
		
		[9] = "Strobe II",
		[10] = "Tension Spring III",
		[11] = "Inhibitor II",
		[12] = "Tension Spring IV",
		[13] = "Heat Capacitor II",
		[14] = "Speedloader",
		[15] = "Speedloader II",
		[16] = "Tension Spring V",
		
		[17] = "Magniplug",
		[18] = "Magniplug II",
	},
	['Ice Attachments'] = {
		[0] = "Mana Booster",
		[1] = "Loudspeaker",
		[2] = "Scanner",
		[3] = "Loudspeaker II",
		[4] = "Tactical Processor",
		[5] = "Tranquilizer",
		[6] = "Ice Maker",
		[7] = "Power Cooler",
		
		[8] = "Loudspeaker III",
		[9] = "Tranquilizer II",
		[10] = "Amplifier",
		[11] = "Loudspeaker IV",
		[12] = "Tranquilizer III",
		[13] = "Amplifier II",
		[14] = "Loudspeaker V",
		[15] = "Tranquilizer IV",
		
		[16] = "Arcanoclutch",
		[17] = "Arcanoclutch II",
	},
	['Wind Attachments'] = {
		[0] = "Accelerator",
		[1] = "Scope",
		[2] = "Pattern Reader",
		[3] = "Accelerator II",
		[4] = "Drum Magazine",
		[5] = "Turbo Charger",
		[6] = "Replicator",
		[7] = "Barrage Turbine",
		
		[8] = "Turbo Charger II",
		[9] = "Accelerator III",
		[10] = "Scope II",
		[11] = "Repeater",
		[12] = "Accelerator IV",
		[13] = "Scope III",
		[14] = "Scope IV",
		[15] = "Truesights",
	},
	['Earth Attachments'] = {
		[0] = "Shock Absorber",
		[1] = "Armor Plate",
		[2] = "Analyzer",
		[3] = "Armor Plate II",
		[4] = "Equalizer",
		[5] = "Schurzen",
		[6] = "Hammermill",
		[7] = "Barrier Module II",
		
		[8] = "Shock Absorber II",
		[9] = "Armor Plate III",
		[10] = "Barrier Module",
		[11] = "Armor Plate IV",
		[12] = "Shock Absorber III",
	},
	['Thunder Attachments'] = {
		[0] = "Stabilizer",
		[1] = "Volt Gun",
		[2] = "Heat Seeker",
		[3] = "Stabilizer II",
		[4] = "Target Marker",
		[5] = "Dynamo",
		[6] = "Coiler",
		[7] = "Galvanizer",
		
		[8] = "Stabilizer III",
		[9] = "Coiler II",
		[10] = "Dynamo II",
		[11] = "Stabilizer IV",
		[12] = "Dynamo III",
		[13] = "Stabilizer V",
	},
	['Water Attachments'] = {
		[0] = "Mana Jammer",
		[1] = "Heatsink",
		[2] = "Stealth Screen",
		[3] = "Mana Jammer II",
		[4] = "Mana Channeler",
		[5] = "Condenser",
		[6] = "Steam Jacket",
		[7] = "Percolator",
		
		[8] = "Mana Jammer III",
		[9] = "Stealth Screen II",
		[10] = "Resister",
		[11] = "Resister II",
		[12] = "Mana Jammer IV",
		[13] = "Mana Channeler II",
	},
	['Light Attachments'] = {
		[0] = "Auto-Repair Kit",
		[1] = "Flashbulb",
		[2] = "Damage Gauge",
		[3] = "Auto-Repair Kit II",
		[4] = "Eraser",
		[5] = "Optic Fiber",
		--[6] = ".",
		[7] = "Vivi-Valve",
		
		[8] = "Vivi-Valve II",
		[9] = "Auto-Repair Kit III",
		[10] = "Arcanic Cell",
		[11] = "Arcanic Cell II",
		[12] = "Auto-Repair Kit IV",
		[13] = "Optic Fiber II",
		[14] = "Damage Gauge II",
	},
	['Dark Attachments'] = {
		[0] = "Mana Tank",
		[1] = "Mana Converter",
		[2] = "Mana Conserver",
		[3] = "Mana Tank II",
		[4] = "Smoke Screen",
		[5] = "Economizer",
		--[6] = ".",
		[7] = "Disruptor",
		
		[8] = "Mana Tank III",
		[9] = "Regulator",
		[10] = "Mana Tank IV",
	},
}